version: '3.7'

services:
  database:
    image: postgres
    container_name: database_dft
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=dft
      - POSTGRES_DB=data_dft
